version: '3.9'

services:
  shortener-app:
    build: ./
    ports:
      - "8007:8007"
    depends_on:
      - db
    environment:
      - host=db
      - DB_PASSWORD=qwerty

  db:
    restart: always
    image: mongo:latest
    volumes:
      - ./.database/mongo/data:/var/lib/mongo/data
    ports:
      - "27017:27017"