directory_name: "thumbnails"
host: "0.0.0.0"
port: "9080"
drop_cache: "yes"
dst: "stdout"

db:
  username: "mongo"
  host: "localhost"
  port: "27017"
  url: "test1-mongo"
  default_database: "videos-db"
  test_database: "videos-db-test"
  collection: "videos"